# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run iOS Tests"
  lane :test do
    scan(scheme: "moltin\ iOS")
    sh("mv test_output/report.junit test_output/report.xml")
  end

  lane :test_tv do
    scan(scheme: "moltin\ tvOS")
    sh("mv test_output/report.junit test_output/report.xml")
  end
end

platform :mac do
  desc "Run macOS Tests"
  lane :test do
    scan(scheme: "moltin\ macOS")
    sh("mv test_output/report.junit test_output/report.xml")
  end
end
